name: CI/CD Pipeline for Portfolio Website to AWS S3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      id-token: write # Required for OIDC authentication to AWS
      contents: read # Allows checking out code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm ci
        working-directory: ./portfolio/

      - name: Build
        run: npm run build
        working-directory: ./portfolio/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::740857577909:role/github-workflow
          aws-region: us-east-1

      - name: Deploy to S3
        # The build output is usually in ./portfolio/build, so we sync from there.
        # Ensure 'build' folder is inside 'portfolio' after npm run build
        run: |
          aws s3 sync ./portfolio/build/ s3://mburu.nkonge --delete --cache-control max-age=31536000
          aws s3 cp ./portfolio/build/index.html s3://mburu.nkonge/index.html --cache-control no-cache
          aws s3 cp ./portfolio/build/asset-manifest.json s3://mburu.nkonge/asset-manifest.json --cache-control no-cache
